const blades = {
    acidic_crystal_spear_blade: {
        name: "Acidic Crystal Spear Blade",
        physATK: 57,
        elemATK: [0, 0, 51],
        weight: 6.4,
        type: "Dagger",
        fable: 376,
        pulse_charge: 9.4,
    },
    acidic_great_curved_sword_blade: {
        name: "Acidic Great Curved Sword Blade",
        physATK: 139,
        elemATK: [0, 0, 0],
        weight: 12.9,
        type: "Greatsword",
        fable: 408,
        pulse_charge: 13.15,
        reinforcements: [1, 1.1, 1.2071, 1.3169, 1.4287, 1.5419, 1.6562, 1.7715, 1.8877, 2.045, 2.122],
    },
    big_pipe_wrench_head: {
        name: "Big Pipe Wrench Head",
        physATK: 156,
        elemATK: [0, 0, 0],
        weight: 17,
        type: "Large Blunt",
        fable: 604,
        pulse_charge: 15.1,
        reinforcements: [1, 1.1, 1.19320, 1.2840, 1.37320, 1.46130, 1.54860, 1.63510, 1.72100, 1.8064, 1.89130],
    },
    black_steel_cutter_blade: {
        name: "Black Steel Cutter Blade",
        physATK: 67,
        elemATK: [0, 65, 0],
        weight: 10.4,
        type: "Greatsword",
        fable: 473,
        pulse_charge: 11.85,
    },
    blind_mans_double_sided_spear: {
        name: "Blind Man's Double-sided Spear",
        physATK: 97,
        elemATK: [0, 0, 0],
        weight: 7.6,
        type: "Sword",
        fable: 391,
        pulse_charge: 9.75,
    },
    bone_cutting_sawblade: {
        name: "Bone-cutting Sawblade",
        physATK: 152,
        elemATK: [0, 0, 0],
        weight: 15.9,
        type: "Greatsword",
        fable: 568,
        pulse_charge: 14.2,
    },
    booster_glaive_blade: {
        name: "Booster Glaive Blade",
        physATK: 131,
        elemATK: [0, 0, 0],
        weight: 11.6,
        type: "Greatsword",
        fable: 566,
        pulse_charge: 12.5,
        reinforcements: [1, 1.1, 1.19320, 1.28400, 1.37320, 1.46130, 1.54860, 1.63510, 1.72100, 1.80640, 1.89130],
    },
    bramble_curved_sword_blade: {
        name: "Bramble Curved Sword Blade",
        physATK: 113,
        elemATK: [0, 0, 0],
        weight: 7.4,
        type: "Sword",
        fable: 403,
        pulse_charge: 11.4,
    },
    carcass_crystal_axe_blade: {
        name: "Carcass Crystal Axe Blade",
        physATK: 64,
        elemATK: [0, 0, 63],
        weight: 12,
        type: "Blunt",
        fable: 376,
        pulse_charge: 12.1,
    },
    circular_electric_chainsaw_blade: {
        name: "Circular Electric Chainsaw Blade",
        physATK: 68,
        elemATK: [61, 0, 0],
        weight: 13.3,
        type: "Blunt",
        fable: 605,
        pulse_charge: 13.35,
    },
    city_longspear_blade: {
        name: "City Longspear Blade",
        physATK: 110,
        elemATK: [0, 0, 0],
        weight: 10.4,
        type: "Sword",
        fable: 452,
        pulse_charge: 11.3,
        reinforcements: [1, 1.1, 1.2071, 1.3169, 1.4287, 1.5419, 1.6562, 1.7715, 1.8877, 2.045, 2.122],
    },
    clock_sword_blade: {
        name: "Clock Sword Blade",
        physATK: 114,
        elemATK: [0, 0, 0],
        weight: 7.6,
        type: "Sword",
        fable: 407,
        pulse_charge: 8.85,
    },
    coil_mjolnir_head: {
        name: "Coil Mjolnir Head",
        physATK: 157,
        elemATK: [0, 0, 0],
        weight: 15.9,
        type: "Large Blunt",
        fable: 583,
        pulse_charge: 16.5,
    },
    cursed_knights_halberd_blade: {
        name: "Cursed Knight's Halberd Blade",
        physATK: 112,
        elemATK: [0, 0, 0],
        weight: 9.9,
        type: "Blunt",
        fable: 461,
        pulse_charge: 10.05,
    },
    dancers_curved_sword_blade: {
        name: "Dancer's Curved Sword Blade",
        physATK: 121,
        elemATK: [0, 0, 0],
        weight: 9.1,
        type: "Greatsword",
        fable: 443,
        pulse_charge: 9.65,
    },
    electric_coil_stick_head: {
        name: "Electric Coil Stick Head",
        physATK: 60,
        elemATK: [56, 0, 0],
        weight: 9.0,
        type: "Blunt",
        fable: 500,
        pulse_charge: 11.05,
    },
    exploding_pickaxe_blade: {
        name: "Exploding Pickaxe Blade",
        physATK: 132,
        elemATK: [0, 0, 0],
        weight: 12.9,
        type: "Large Blunt",
        fable: 525,
        pulse_charge: 13.15,
    },
    fire_axe_blade: {
        name: "Fire Axe Blade",
        physATK: 119,
        elemATK: [0, 0, 0],
        weight: 8.8,
        type: "Blunt",
        fable: 437,
        pulse_charge: 9.5,
    },
    greatsword_of_fate_blade: {
        name: "Greatsword of Fate Blade",
        physATK: 121,
        elemATK: [0, 0, 0],
        weight: 10.6,
        type: "Greatsword",
        fable: 478,
        pulse_charge: 10.4,
    },
    krat_police_baton_head: {
        name: "Krat Police Baton Head",
        physATK: 104,
        elemATK: [0, 0, 0],
        weight: 7.9,
        type: "Blunt",
        fable: 323,
        pulse_charge: 10.4,
    },
    live_puppets_axe_blade: {
        name: "Live Puppet's Axe Blade",
        physATK: 174,
        elemATK: [0, 0, 0],
        weight: 18.8,
        type: "Greatsword",
        fable: 720,
        pulse_charge: 15.85,
    },
    master_chefs_knife_blade: {
        name: "Master Chef's Knife Blade",
        physATK: 104,
        elemATK: [0, 0, 0],
        weight: 5.8,
        type: "Dagger",
        fable: 359,
        pulse_charge: 8.95,
        reinforcements: [1, 1.1, 1.2071, 1.3169, 1.4287, 1.5419, 1.6562, 1.7715, 1.8877, 2.045, 2.122]
    },
    military_shovel_blade: {
        name: "Military Shovel Blade",
        physATK: 119,
        elemATK: [0, 0, 0],
        weight: 9.9,
        type: "Blunt",
        fable: 461,
        pulse_charge: 10.05,
    },
    pistol_rock_drill_blade: {
        name: "Pistol Rock Drill Blade",
        physATK: 108,
        elemATK: [0, 0, 0],
        weight: 10.5,
        type: "Dagger",
        fable: 476,
        pulse_charge: 11.9,
    },
    puppet_saber_blade: {
        name: "Puppet Saber Blade",
        physATK: 112,
        elemATK: [0, 0, 0],
        weight: 7.3,
        type: "Sword",
        fable: 400,
        pulse_charge: 10,
    },
    salamander_dagger_blade: {
        name: "Salamander Dagger Blade",
        physATK: 45,
        elemATK: [0, 45, 0],
        weight: 6.6,
        type: "Dagger",
        fable: 363,
        pulse_charge: 10.25,
    },
    spear_of_honor_blade: {
        name: "Spear of Honor Blade",
        physATK: 124,
        elemATK: [0, 0, 0],
        weight: 10.7,
        type: "Greatsword",
        fable: 373,
        pulse_charge: 12,
    },
    tyrant_murderers_dagger_blade: {
        name: "Tyrant Murderer's Dagger Blade",
        physATK: 93,
        // elemATK array order: [blitz, fire, acid]
        elemATK: [0, 0, 0],
        weight: 4.9,
        type: "Dagger",
        fable: 324,
        pulse_charge: 8.1,
    },
    wintry_rapier_blade: {
        name: "Wintry Rapier Blade",
        physATK: 98,
        // elemATK array order: [blitz, fire, acid]
        elemATK: [0, 0, 0],
        weight: 5,
        type: "Sword",
        fable: 330,
        pulse_charge: 8.25,
    }
};
